AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample src Template for SpringNative
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  PACFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: pac
      Handler: exampleFunction
      Runtime: java11
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
Outputs:
  PACFunction:
    Description: "PAC Lambda Function ARN"
    Value: !GetAtt PACFunction.Arn
  PACFunctionIamRole:
    Description: "Implicit IAM Role created for PAC function"
    Value: !GetAtt PACFunctionRole.Arn